name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Set up Docker Buildx (for multi-platform builds)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: |
          npm install -g snyk

      # Authenticate to Snyk
      - name: Authenticate to Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Build and push Docker images for frontend
      - name: Build and push frontend image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest ./frontend --push

      # Build and push Docker images for backend
      - name: Build and push backend image
        run: |
          docker buildx build --platform linux/amd64 -t ${{ secrets.DOCKER_USERNAME }}/my-backend:latest ./backend --push

      # Run Snyk vulnerability scan for frontend
      - name: Run Snyk vulnerability scan for frontend
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

      # Run Snyk vulnerability scan for backend
      - name: Run Snyk vulnerability scan for backend
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
