version: '3.7'

services:
  # Frontend service
  frontend:
    build:
      context: ./frontend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Backend service
  backend:
    build:
      context: ./backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  # Prometheus for monitoring
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - app-network

  # Snyk for vulnerability scanning
  snyk:
    image: snyk/snyk-cli:latest
    container_name: snyk
    entrypoint: ["snyk", "test", "--all-projects"]
    volumes:
      - ./frontend:/workspace/frontend
      - ./backend:/workspace/backend
    networks:
      - app-network
    environment:
      - SNYK_TOKEN=your_snyk_token_here

networks:
  app-network:
    driver: bridge

# Optional: You could add a volume for persistence, etc.
volumes:
  prometheus-data:
    driver: local
