name: CI/CD Pipeline with Snyk, Docker, and Push

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Docker Buildx for multi-platform support (optional, remove if not needed)
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # Docker login using GitHub Action
      - name: Docker login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Build the backend image
      - name: Build Backend Docker image
        run: |
          cd backend
          docker build -t ngowe9/backend:latest .

      # Build the frontend image
      - name: Build Frontend Docker image
        run: |
          cd frontend
          docker build -t ngowe9/frontend:latest .

      # Push the backend image to Docker Hub
      - name: Push Backend Docker image
        run: |
          docker push ngowe9/backend:latest

      # Push the frontend image to Docker Hub
      - name: Push Frontend Docker image
        run: |
          docker push ngowe9/frontend:latest

      # Run Snyk to test for vulnerabilities in the backend image
      - name: Snyk Test Backend Image
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk container test ngowe9/backend:latest

      # Run Snyk to test for vulnerabilities in the frontend image
      - name: Snyk Test Frontend Image
        run: |
          snyk auth ${{ secrets.SNYK_TOKEN }}
          snyk container test ngowe9/frontend:latest
