name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
      # Checkout the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # Install Snyk CLI
      - name: Install Snyk CLI
        run: npm install -g snyk

      # Authenticate to Snyk
      - name: Authenticate to Snyk
        run: snyk auth ${{ secrets.SNYK_TOKEN }}

      # Build and push frontend image
      - name: Build and push frontend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest ./frontend
          docker push ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest

      # Build and push backend image
      - name: Build and push backend image
        run: |
          docker build -t ${{ secrets.DOCKER_USERNAME }}/backend_image:latest ./backend
          docker push ${{ secrets.DOCKER_USERNAME }}/backend_image:latest

      # Run Snyk vulnerability scan for frontend
      - name: Run Snyk vulnerability scan for frontend
        id: snyk-frontend
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest

      # Run Snyk vulnerability scan for backend
      - name: Run Snyk vulnerability scan for backend
        id: snyk-backend
        run: snyk container test ${{ secrets.DOCKER_USERNAME }}/backend_image:latest

      # Fail the job if vulnerabilities are found (Frontend)
      - name: Fail job if vulnerabilities are found (Frontend)
        if: steps.snyk-frontend.outcome == 'failure'
        run: exit 1

      # Fail the job if vulnerabilities are found (Backend)
      - name: Fail job if vulnerabilities are found (Backend)
        if: steps.snyk-backend.outcome == 'failure'
        run: exit 1
