name: Web App CI/CD Pipeline

on:
  push:
    branches:
      - main  # Trigger on push to the main branch
  pull_request:
    branches:
      - main  # Trigger on pull request targeting the main branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Cache Docker layers
      uses: actions/cache@v2
      with:
        path: /tmp/.buildx-cache
        key: ${{ runner.os }}-buildx-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-buildx-

    - name: Build Backend Docker Image
      run: |
        docker build -t ngowe9/backend:latest ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t ngowe9/frontend:latest ./frontend

    - name: Push Docker Images to Docker Hub
      run: |
        docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
        docker push ngowe9/backend:latest
        docker push ngowe9/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job runs first

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
