name: CI/CD Pipeline

# This section defines the event(s) that trigger the workflow
on:
  push:
    branches:
      - main  # Trigger the workflow on push to the 'main' branch
  pull_request:
    branches:
      - main  # Trigger the workflow on PRs to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build Docker image
        run: |
          docker build -t your-image-name .

      - name: Run tests
        run: |
          # Run any tests you may have
          echo "Running tests"

  snyk_scan:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Set up Snyk
        uses: snyk/actions/setup@v1

      - name: Run Snyk test
        run: snyk test --all-projects
