name: Web App CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Backend Docker Image
      run: |
        docker build -t ngowe9/backend:latest ./backend

    - name: Build Frontend Docker Image
      run: |
        docker build -t ngowe9/frontend:latest ./frontend

    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    - name: Snyk Container Security Scan - Backend
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk container test ngowe9/backend:latest || echo "Snyk scan completed with vulnerabilities"

    - name: Snyk Container Security Scan - Frontend
      run: |
        snyk auth ${{ secrets.SNYK_TOKEN }}
        snyk container test ngowe9/frontend:latest || echo "Snyk scan completed with vulnerabilities"

    - name: Docker login and Push Images
      run: |
        echo ${{ secrets.DOCKER_PASSWORD }} | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        docker push ngowe9/backend:latest
        docker push ngowe9/frontend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Deploy to Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
