name: Simple CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Install Snyk CLI
    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    # Authenticate to Snyk
    - name: Authenticate to Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Remove buildx plugin if it's installed
    - name: Remove buildx plugin
      run: |
        rm -f ~/.docker/cli-plugins/docker-buildx

    # Build frontend image
    - name: Build frontend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest ./frontend

    # Build backend image
    - name: Build backend image
      run: |
        docker build -t ${{ secrets.DOCKER_USERNAME }}/backend_image:latest ./backend

    # Push frontend image to Docker Hub
    - name: Push frontend image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest

    # Push backend image to Docker Hub
    - name: Push backend image to Docker Hub
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/backend_image:latest

    # Run Snyk vulnerability scan for frontend
    - name: Run Snyk vulnerability scan for frontend
      id: snyk-frontend
      run: snyk container test ${{ secrets.DOCKER_USERNAME }}/frontend_image:latest

    # Run Snyk vulnerability scan for backend
    - name: Run Snyk vulnerability scan for backend
      id: snyk-backend
      run: snyk container test ${{ secrets.DOCKER_USERNAME }}/backend_image:latest

    # Fail the job if vulnerabilities are found (Frontend)
    - name: Fail job if vulnerabilities are found (Frontend)
      if: steps.snyk-frontend.outcome == 'failure'
      run: exit 1

    # Fail the job if vulnerabilities are found (Backend)
    - name: Fail job if vulnerabilities are found (Backend)
      if: steps.snyk-backend.outcome == 'failure'
      run: exit 1
