jobs:
  build_and_scan:
    runs-on: ubuntu-latest

    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Authenticate to Snyk
    - name: Authenticate to Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Build and scan the frontend image
    - name: Build frontend image
      run: |
        docker build -t my-frontend ./frontend
        docker tag my-frontend:latest ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Run Snyk vulnerability scan for frontend
      run: snyk container test ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    # Build and scan the backend image
    - name: Build backend image
      run: |
        docker build -t my-backend ./backend
        docker tag my-backend:latest ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

    - name: Run Snyk vulnerability scan for backend
      run: snyk container test ${{ secrets.DOCKER_USERNAME }}/my-backend:latest

    # Push images to Docker Hub if no vulnerabilities are found
    - name: Push frontend image to Docker Hub
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-frontend:latest

    - name: Push backend image to Docker Hub
      if: success()
      run: |
        docker push ${{ secrets.DOCKER_USERNAME }}/my-backend:latest
