name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build_and_scan:
    runs-on: ubuntu-latest
    
    steps:
    # Checkout the code
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Docker Buildx (for multi-platform builds)
    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    # Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Install Snyk CLI
    - name: Install Snyk CLI
      run: |
        npm install -g snyk

    # Authenticate with Snyk
    - name: Authenticate with Snyk
      run: snyk auth ${{ secrets.SNYK_TOKEN }}

    # Build Docker images for frontend and backend
    - name: Build frontend image
      run: |
        docker build -t ngowe9/my-frontend ./frontend
        docker tag ngowe9/my-frontend:latest ngowe9/my-frontend:latest

    - name: Build backend image
      run: |
        docker build -t ngowe9/my-backend ./backend
        docker tag ngowe9/my-backend:latest ngowe9/my-backend:latest

    # Scan Docker images for vulnerabilities using Snyk
    - name: Run Snyk vulnerability scan for frontend
      run: snyk container test ngowe9/my-frontend:latest

    - name: Run Snyk vulnerability scan for backend
      run: snyk container test ngowe9/my-backend:latest

    # Push the images to Docker Hub (if no vulnerabilities are found)
    - name: Push frontend image to Docker Hub
      if: success()
      run: |
        docker push ngowe9/my-frontend:latest

    - name: Push backend image to Docker Hub
      if: success()
      run: |
        docker push ngowe9/my-backend:latest

  deploy:
    runs-on: ubuntu-latest
    needs: build_and_scan
    
    steps:
    # Checkout code
    - name: Checkout code
      uses: actions/checkout@v2

    # Deploy using Docker Compose
    - name: Deploy with Docker Compose
      run: |
        docker-compose -f docker-compose.yml up -d
